process.roles=broker,controller
node.id=1
controller.quorum.voters=1@kafka-broker:9094
listeners=PLAINTEXT://:29092,SSL://:29093,CONTROLLER://:9094
advertised.listeners=PLAINTEXT://localhost:29092,SSL://localhost:29093
listener.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL,CONTROLLER:CONTROLLER
inter.broker.listener.name=SSL
controller.listener.names=CONTROLLER

ssl.enabled.protocols=TLSv1.2
ssl.cipher.suites=TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA
ssl.keystore.type=PEM
ssl.keystore.location=/etc/kafka/secrets/kafka.keystore.pem
ssl.client.auth=none
