events {}

http {
  upstream whoami_upstream {
    server whoami:80;
  }

  server {
    listen 443 ssl;
    server_name mtls.chaos.local;

    ssl_certificate     /etc/nginx/certs/mtls.crt;
    ssl_certificate_key /etc/nginx/certs/mtls.key;

    # Trust the step-ca root
    ssl_client_certificate /home/step/certs/root_ca.crt;
    ssl_verify_client on;

    location / {
      proxy_pass http://whoami_upstream;
      proxy_set_header Host $host;
    }
  }
}
