events {}
http {
  server {
    listen 443 ssl;
    server_name sha1.chaos.local;

    ssl_certificate     /etc/nginx/scenarios/sha1/leaf.crt;
    ssl_certificate_key /etc/nginx/scenarios/sha1/leaf.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
      return 200 "OK - sha1 signed leaf cert\n";
    }
  }
}