events {}
http {
  server {
    listen 443 ssl;
    server_name missing-intermediate.chaos.local;

    ssl_certificate     /etc/nginx/scenarios/missing-intermediate/leaf.crt;
    ssl_certificate_key /etc/nginx/scenarios/missing-intermediate/leaf.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
      return 200 "OK - missing intermediate\n";
    }
  }
}