"""Phase 222 / BRAND-05 -- the "Generated by" brand colophon on on-disk reports.

HTML and PDF carry the Paper SVG (quirk-logo-dark.svg) as a data URI in the footer, which
now prints (D-22). DOCX ends with a paragraph holding the Ink PNG (D-13). The client cover
logo (report.branding.logo_path) is unchanged and the colophon is never recoloured (D-19).

PDF leg honesty: ``test_pdf_colophon_drawn`` executes for real in the advisory Browser E2E
job and locally where Chromium is installed. In the required Linux Full Suite job it skips
via ``_render_or_skip`` (registered in tests/skip_registry.py). A skip is not a pass.
"""
from __future__ import annotations

import base64
import os
import re
import struct
import zlib
from types import SimpleNamespace
from unittest import mock

import pytest

_ASSETS = os.path.join(os.path.dirname(__file__), "..", "quirk", "reports", "assets")


def _make_minimal_cfg(report=None):
    # `report` pinned explicitly (MagicMock spec auto-vivify trap).
    return SimpleNamespace(
        assessment=SimpleNamespace(
            name="Test Org",
            report_owner="Test Owner",
            data_classification="CONFIDENTIAL",
            timezone="UTC",
            logo_path=None,
        ),
        output=SimpleNamespace(directory="/tmp/quirk_test_report_colophon"),
        report=report,
    )


def _report_cfg(**overrides):
    fields = dict(
        logo_path=None, client_name=None, engagement_name=None,
        prepared_by=None, cover_date=None, confidentiality_line=None,
    )
    fields.update(overrides)
    return SimpleNamespace(template_dir=None, branding=SimpleNamespace(**fields))


def _png_bytes(r: int, g: int, b: int) -> bytes:
    def chunk(tag: bytes, data: bytes) -> bytes:
        return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data))

    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", 1, 1, 8, 2, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(bytes([0, r, g, b])))
        + chunk(b"IEND", b"")
    )


def _render_html(tmp_path, cfg=None, name="report.html") -> str:
    from quirk.reports.html_renderer import render_html_report

    path = str(tmp_path / name)
    render_html_report(
        path=path, cfg=cfg or _make_minimal_cfg(report=None), findings=[],
        score={"score": None}, conf={}, endpoints=[], roadmap_items=[], exec_content=None,
    )
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def _footer(html: str) -> str:
    m = re.search(r'<footer class="footer">.*?</footer>', html, re.S)
    assert m, "footer not found"
    return m.group(0)


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------


def test_html_colophon_uses_paper_svg_data_uri(tmp_path):
    footer = _footer(_render_html(tmp_path))
    assert '<img class="colophon-logo"' in footer
    assert 'alt="QU.I.R.K."' in footer
    m = re.search(r'src="data:image/svg\+xml;base64,([A-Za-z0-9+/=]+)"', footer)
    assert m, "colophon svg data URI missing"
    with open(os.path.join(_ASSETS, "quirk-logo-dark.svg"), "rb") as fh:
        assert base64.b64decode(m.group(1)) == fh.read()
    assert "Generated by" in footer and "Quantum Infrastructure Readiness Kit" in footer
    assert "<strong>QU.I.R.K.</strong>" not in footer


def test_html_colophon_no_png_data_uri_without_client_logo(tmp_path):
    assert "data:image/png;base64," not in _render_html(tmp_path)


def test_html_footer_not_print_hidden(tmp_path):
    html = _render_html(tmp_path)
    print_block = html[html.index("@media print"):]
    print_block = print_block[: print_block.index("</style>")]
    assert not re.search(r"\.footer\s*\{\s*display:\s*none", print_block)
    assert re.search(r"\.footer\s*\{[^}]*break-inside:\s*avoid", print_block)


def test_html_colophon_text_fallback_when_asset_unreadable(tmp_path):
    with mock.patch("quirk.reports.html_renderer._load_colophon_logo_b64", return_value=None):
        footer = _footer(_render_html(tmp_path))
    assert "<strong>QU.I.R.K.</strong>" in footer
    assert "<img" not in footer


def test_html_colophon_loader_never_raises(tmp_path):
    from quirk.reports import html_renderer

    with mock.patch.object(html_renderer, "_ASSETS_DIR", str(tmp_path / "nope")):
        assert html_renderer._load_colophon_logo_b64() is None


# ---------------------------------------------------------------------------
# PDF
# ---------------------------------------------------------------------------


def _render_or_skip(html_path: str, pdf_path: str) -> None:
    from quirk.reports.html_renderer import render_pdf_report

    try:
        result = render_pdf_report(html_path, pdf_path)
    except AttributeError as exc:
        if "PlaywrightContextManager" not in str(exc) or "_playwright" not in str(exc):
            raise
        pytest.skip(f"TRIAGE-149 Cluster 2 Playwright singleton contamination: {exc}")
    if result is False:
        pytest.skip(
            "render_pdf_report() degraded to False (no Chromium in Linux Full Suite by design), "
            "so no PDF exists to assert the Phase 222 colophon against. Runs for real in the "
            "Browser E2E job (advisory) and locally."
        )
    assert os.path.getsize(pdf_path) > 0


def _has_fill(streams: str, rgb, tol=0.5 / 255 + 1e-4) -> bool:
    for m in re.finditer(r"(-?[\d.]+) (-?[\d.]+) (-?[\d.]+) rg\b", streams):
        got = tuple(float(x) for x in m.groups())
        if all(abs(g - w / 255.0) <= tol for g, w in zip(got, rgb)):
            return True
    return False


def test_pdf_colophon_drawn(tmp_path):
    html = _render_html(tmp_path)
    html_path = str(tmp_path / "report.html")
    pdf_path = str(tmp_path / "report.pdf")
    _render_or_skip(html_path, pdf_path)

    import pypdf

    reader = pypdf.PdfReader(pdf_path)
    streams = ""
    text = ""
    for page in reader.pages:
        contents = page.get_contents()
        if contents is not None:
            streams += contents.get_data().decode("latin-1") + "\n"
        text += (page.extract_text() or "") + "\n"
    assert _has_fill(streams, (0x7F, 0xE0, 0x01)), "Signal #7FE001 fill absent from PDF"
    assert _has_fill(streams, (0xF4, 0xF5, 0xF9)), "Paper fill absent from PDF"
    assert "Generated by" in text
    assert "Quantum Infrastructure Readiness Kit" in text
    assert html  # rendered


# ---------------------------------------------------------------------------
# DOCX (D-13) and cover-logo-unchanged regression (D-19)
# ---------------------------------------------------------------------------

_COVER_PARA_IDX = 0  # recorded on pre-phase code: doc.add_picture makes its own first paragraph
_W = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"


def _render_docx(tmp_path, logo=False, **branding):
    from docx import Document

    from quirk.reports.docx_renderer import render_docx_report

    if logo:
        lp = tmp_path / "logo.png"
        lp.write_bytes(_png_bytes(255, 0, 0))
        branding["logo_path"] = str(lp)
    cfg = _make_minimal_cfg(report=_report_cfg(**branding))
    path = str(tmp_path / "report.docx")
    assert render_docx_report(path=path, cfg=cfg, findings=[]) is True
    return Document(path)


def test_docx_colophon_last_paragraph(tmp_path):
    doc = _render_docx(tmp_path)
    last = doc.paragraphs[-1]
    assert last._p.xpath(".//w:drawing")
    assert "Generated by" in last.text
    assert "Quantum Infrastructure Readiness Kit" in last.text
    extent = last._p.xpath(".//wp:extent")[0]
    assert int(extent.get("cy")) == 228600


def test_docx_picture_count_with_and_without_cover_logo(tmp_path):
    assert len(_render_docx(tmp_path, logo=True).inline_shapes) == 2
    sub = tmp_path / "nologo"
    sub.mkdir()
    assert len(_render_docx(sub).inline_shapes) == 1


def test_docx_colophon_embed_failure_never_crashes(tmp_path):
    with mock.patch("quirk.reports.docx_renderer._COLOPHON_PNG", str(tmp_path / "missing.png")):
        doc = _render_docx(tmp_path)
    assert len(doc.inline_shapes) == 0


def test_cover_logo_unchanged_with_colophon_html(tmp_path):
    lp = tmp_path / "logo.png"
    lp.write_bytes(_png_bytes(255, 0, 0))
    html = _render_html(tmp_path, cfg=_make_minimal_cfg(report=_report_cfg(logo_path=str(lp))))
    cover = html.index("data:image/png;base64,")
    assert cover < html.index('<footer class="footer">')
    assert "colophon-logo" in _footer(html)
    assert "data:image/png;base64," not in _footer(html)


def test_cover_logo_unchanged_with_colophon_docx(tmp_path):
    doc = _render_docx(tmp_path, logo=True)
    assert doc.paragraphs[_COVER_PARA_IDX]._p.xpath(".//w:drawing")
    assert doc.paragraphs[-1]._p.xpath(".//w:drawing")
    assert len(doc.paragraphs) - 1 != _COVER_PARA_IDX


def test_docx_section_footer_unchanged(tmp_path):
    doc = _render_docx(
        tmp_path, client_name="Acme Client", confidentiality_line="STRICTLY CONFIDENTIAL"
    )
    footer = doc.sections[0].footer.paragraphs[0]
    assert "Acme Client" in footer.text and "STRICTLY CONFIDENTIAL" in footer.text
    assert not footer._p.xpath(".//w:drawing")
