"""CBOM-02 classifier coverage gate + regen-mode coverage report.

Two tests:

1. ``test_no_unknown_classifications_across_lab_profiles`` (the gate)
   — Walks every algorithm component emitted by ``build_cbom()`` for every
     one of the 18 chaos lab profiles in ``tests._cbom_profiles.PROFILE_ENDPOINTS``
     and asserts that ``classify_algorithm(name)`` returns a non-UNKNOWN
     primitive for every observed name (the JWT ``alg:none`` sentinel is the
     single intentional exception per RESEARCH Pitfall #4).

2. ``test_regenerate_coverage_report`` (the regen-mode generator)
   — Skipped unless ``REGEN_CBOM_COVERAGE=1``. Writes a deterministic
     Markdown report at ``docs/cbom-classifier-coverage.md`` listing every
     observed algorithm with primitive, NIST level, classical bits, and
     source profile(s). Re-running the regen with no underlying changes
     produces a byte-identical file (zero git diff).

Both tests import the SAME ``PROFILE_ENDPOINTS`` dict from
``tests._cbom_profiles`` that Plan 02's schema-validation harness imports —
single source of truth, no local duplication (M4 fix per checker feedback).
"""
from __future__ import annotations

import os
from pathlib import Path

import pytest

from cyclonedx.model.crypto import CryptoPrimitive

from quirk.cbom.builder import build_cbom
from quirk.cbom.classifier import classify_algorithm
from tests._cbom_profiles import PROFILE_ENDPOINTS


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _collect_algorithm_names_by_profile() -> dict[str, set[str]]:
    """For every profile, build its CBOM and collect algorithm component names.

    Returns a mapping ``algorithm_name -> {profile, profile, ...}``.
    """
    seen: dict[str, set[str]] = {}
    for profile, fn in PROFILE_ENDPOINTS.items():
        bom = build_cbom(fn())
        for c in bom.components:
            cp = getattr(c, "crypto_properties", None)
            if cp and cp.asset_type and cp.asset_type.value == "algorithm":
                seen.setdefault(c.name, set()).add(profile)
    return seen


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


def test_no_unknown_classifications_across_lab_profiles() -> None:
    """Gate: every algorithm surfaced by any of the 18 lab profiles must
    classify to a non-UNKNOWN primitive (Pitfall #4 sentinel ``alg:none``
    excepted).
    """
    seen = _collect_algorithm_names_by_profile()

    unknowns: list[tuple[str, list[str]]] = []
    for name, profiles in sorted(seen.items()):
        primitive, _, _ = classify_algorithm(name)
        # JWT alg:none is an intentional UNKNOWN sentinel (Pitfall #4).
        if primitive == CryptoPrimitive.UNKNOWN and name.lower() != "none":
            unknowns.append((name, sorted(profiles)))

    assert not unknowns, (
        "In-scope algorithms classified as UNKNOWN — add rows to "
        "_ALGORITHM_TABLE in quirk/cbom/classifier.py: "
        f"{unknowns}"
    )


@pytest.mark.slow
@pytest.mark.skipif(
    os.environ.get("REGEN_CBOM_COVERAGE") != "1",
    reason="set REGEN_CBOM_COVERAGE=1 to regenerate docs/cbom-classifier-coverage.md",
)
def test_regenerate_coverage_report() -> None:
    """Regen mode: deterministic Markdown report covering every algorithm
    surfaced by ``build_cbom()`` against any of the 18 chaos lab profiles
    (D-05).
    """
    seen = _collect_algorithm_names_by_profile()

    rows: list[tuple[str, str, str, str, str]] = []
    for name, profiles in sorted(seen.items()):
        primitive, nist, classical = classify_algorithm(name)
        rows.append((
            name,
            primitive.name,
            "" if nist is None else str(nist),
            "" if classical is None else str(classical),
            ", ".join(sorted(profiles)),
        ))

    lines = [
        "# CBOM Classifier Coverage Report",
        "",
        "Generated by `tests/test_cbom_classifier_coverage.py::test_regenerate_coverage_report`.",
        "Run `REGEN_CBOM_COVERAGE=1 pytest tests/test_cbom_classifier_coverage.py::test_regenerate_coverage_report -s -m \"\"` to refresh.",
        "",
        "Per Phase 42 / D-05 — every algorithm surfaced by `build_cbom()` against any of the 18 chaos lab profiles.",
        "",
        "| Algorithm Name | Primitive | NIST Level | Classical Bits | Surfaced By Profiles |",
        "|----------------|-----------|------------|----------------|-----------------------|",
    ]
    for name, prim, nist, classical, profiles in rows:
        lines.append(f"| {name} | {prim} | {nist} | {classical} | {profiles} |")
    lines.append("")  # trailing newline

    out = Path(__file__).resolve().parent.parent / "docs" / "cbom-classifier-coverage.md"
    out.write_text("\n".join(lines))
