events {}
http {
  server {
    listen 443 ssl;
    server_name rsa1024.chaos.local;

    ssl_certificate     /etc/nginx/scenarios/rsa1024/leaf.crt;
    ssl_certificate_key /etc/nginx/scenarios/rsa1024/leaf.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
      return 200 "OK - rsa1024 leaf cert\n";
    }
  }
}