"""quirk errors — print the operator error-code reference (Phase 68 UX-01)."""
from __future__ import annotations

import argparse
import sys
from typing import Iterable

from rich.console import Console
from rich.table import Table

from quirk.errors import ERROR_REGISTRY, ErrorEntry, format_error


def _normalize_code(raw: str) -> str:
    """Accept 'QRK-TLS-001' or 'TLS-001'; return the registry key 'TLS-001'."""
    return raw[4:] if raw.startswith("QRK-") else raw


def _domain_of(code: str) -> str:
    return code.split("-", 1)[0]


def _filtered_entries(domain: str | None) -> list[tuple[str, ErrorEntry]]:
    items = sorted(ERROR_REGISTRY.items(), key=lambda kv: kv[0])
    if domain:
        wanted = domain.upper()
        items = [(k, v) for k, v in items if _domain_of(k) == wanted]
    return items


def _print_table(domain: str | None, console: Console) -> None:
    entries = _filtered_entries(domain)
    if not entries:
        console.print(f"[yellow]No error codes found for domain {domain!r}.[/yellow]")
        sys.exit(1)

    title = "QU.I.R.K. Error Codes"
    if domain:
        title += f" — domain: {domain.upper()}"
    table = Table(title=title, show_header=True, header_style="bold")
    table.add_column("Code", style="bold")
    table.add_column("Cause")
    table.add_column("Fix")

    current_domain: str | None = None
    for code, entry in entries:
        d = _domain_of(code)
        if d != current_domain:
            # Section row for domain boundary (when listing all domains)
            if not domain:
                table.add_section()
            current_domain = d
        table.add_row(f"QRK-{code}", entry.cause, entry.fix)

    console.print(table)


def _lookup_single(raw_code: str, console: Console) -> None:
    code = _normalize_code(raw_code)
    if code not in ERROR_REGISTRY:
        console.print(f"[red]Unknown error code: QRK-{code}[/red]")
        console.print("Run `quirk errors` to list all known codes.")
        sys.exit(1)
    entry = ERROR_REGISTRY[code]
    console.print(format_error(code))
    console.print(f"[bold]Domain:[/bold] {_domain_of(code)}")
    console.print(f"[bold]Cause:[/bold]  {entry.cause}")
    console.print(f"[bold]Fix:[/bold]    {entry.fix}")


def _dump_markdown() -> str:
    lines: list[str] = [
        "# QU.I.R.K. Error Code Reference",
        "",
        "_Generated by `quirk errors --dump-md`. Do not edit by hand._",
        "",
        "Wire format: `[QRK-<DOMAIN>-NNN] <cause> Fix: <fix>`",
        "",
    ]
    current_domain: str | None = None
    for code, entry in sorted(ERROR_REGISTRY.items()):
        domain = _domain_of(code)
        if domain != current_domain:
            lines.append("")
            lines.append(f"## {domain}")
            lines.append("")
            lines.append("| Code | Cause | Fix |")
            lines.append("|------|-------|-----|")
            current_domain = domain
        lines.append(f"| QRK-{code} | {entry.cause} | {entry.fix} |")
    lines.append("")  # trailing newline
    return "\n".join(lines)


def run_errors(argv: list[str]) -> None:
    """quirk errors entrypoint. argv is sys.argv[2:] (after the subcommand name)."""
    parser = argparse.ArgumentParser(
        prog="quirk errors",
        description="Print the QU.I.R.K. operator error code reference.",
    )
    parser.add_argument(
        "code",
        nargs="?",
        help="Optional positional: look up a single code (e.g. QRK-TLS-001 or TLS-001).",
    )
    parser.add_argument(
        "--domain",
        help="Filter the table to a single domain (INSTALL, TLS, SSH, JWT, CLOUD, DB, SCHED, CBOM, DASHBOARD).",
    )
    parser.add_argument(
        "--dump-md",
        action="store_true",
        dest="dump_md",
        help="Print the Markdown reference to stdout (used by docs/error-codes.md regeneration).",
    )
    args = parser.parse_args(argv)

    if args.dump_md:
        # Plain print (no Rich) so stdout redirect produces clean Markdown.
        print(_dump_markdown())
        sys.exit(0)

    console = Console()
    if args.code:
        _lookup_single(args.code, console)
        sys.exit(0)

    _print_table(args.domain, console)
    sys.exit(0)
