events {}
http {
  server {
    listen 443 ssl;
    server_name untrusted-ca.chaos.local;
    ssl_certificate     /etc/nginx/scenarios/untrusted-ca/leaf.crt;
    ssl_certificate_key /etc/nginx/scenarios/untrusted-ca/leaf.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    location / { return 200 "OK - tls-cert-untrusted-ca\n"; }
  }
}
