events {}
http {
  server {
    listen 443 ssl;
    server_name selfsigned.chaos.local;
    ssl_certificate     /etc/nginx/certs/selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/selfsigned.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    location / { return 200 "OK - tls-cert-selfsigned\n"; }
  }
}
