import { describe, it, expect, beforeEach, afterEach, vi } from "vitest"
import { render, screen, cleanup } from "@testing-library/react"

// Mutable hook stubs — tests assign values before render.
let scanDataReturn: { data: unknown; loading: boolean; error: string | null } = {
  data: null,
  loading: true,
  error: null,
}
let qrammReturn: {
  scoreResult: unknown
  complianceRows: unknown
  loading: boolean
  error: string | null
} = { scoreResult: null, complianceRows: null, loading: true, error: null }

vi.mock("@/hooks/useScanData", () => ({
  useScanData: () => scanDataReturn,
}))
vi.mock("@/hooks/useQRAMMPrintData", () => ({
  useQRAMMPrintData: () => qrammReturn,
}))

// SCORE-04 / D-09/D-10 (184.4): optional capReason param — undefined (default)
// documents the uncapped case, a string documents the capped case.
function makeScanFixture(capReason?: string) {
  return {
    meta: { scan_id: "1", scanned_at: "2026-05-15T00:00:00Z", total_endpoints: 0, total_findings: 0 },
    score: {
      score: 50, rating: "Moderate", rating_cap_reason: capReason,
      subscores: { hygiene: 0, modern_tls: 0, identity_trust: 0, agility_signals: 0, data_at_rest: 0, data_in_motion: 0 },
      drivers: [],
    },
    confidence: { confidence_score: 0, confidence_rating: "Low", factor_breakdown: {} },
    findings: [],
    certificates: [],
    cbom_components: [],
    roadmap: { nodes: [], edges: [] },
    identity_findings: [],
    motion_findings: [],
    dar_findings: [],
  }
}

beforeEach(() => {
  document.body.removeAttribute("data-ready")
})
afterEach(() => {
  cleanup()
  document.body.removeAttribute("data-ready")
})

async function renderPrint() {
  scanDataReturn = { data: makeScanFixture(), loading: false, error: null }
  qrammReturn = { scoreResult: null, complianceRows: null, loading: false, error: null }
  const { PrintPage } = await import("@/pages/print")
  return render(<PrintPage />)
}

describe("PrintPage - D-18 colophon", () => {
  it("renders the Generated by colophon with the QU.I.R.K. logo", async () => {
    const { container } = await renderPrint()
    const img = screen.getByAltText("QU.I.R.K.")
    expect(container.querySelector(".quirk-print")).toContainElement(img)
    expect(img.getAttribute("src")).toContain("quirk-logo")
    const colophon = img.closest(".print-colophon")
    expect(colophon).not.toBeNull()
    expect(colophon?.textContent).toContain("Generated by")
    expect(colophon?.textContent).toContain("Quantum Infrastructure Readiness Kit")
  })

  it("colophon logo is at least 24px tall", async () => {
    await renderPrint()
    const img = screen.getByAltText("QU.I.R.K.")
    expect(Number(img.getAttribute("height"))).toBeGreaterThanOrEqual(24)
  })

  it("colophon does not repeat the QU.I.R.K. name as text", async () => {
    const { container } = await renderPrint()
    const colophon = container.querySelector(".print-colophon")
    expect(colophon).not.toBeNull()
    expect(colophon?.textContent).not.toContain("QU.I.R.K.")
  })
})
