events {}
http {
  server {
    listen 443 ssl;
    server_name expired.chaos.local;
    ssl_certificate     /etc/nginx/certs/expired.crt;
    ssl_certificate_key /etc/nginx/certs/expired.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    location / { return 200 "OK - tls-cert-expired\n"; }
  }
}
