events {}

http {
  server {
    listen 443 ssl;
    server_name modern.chaos.local;

    ssl_certificate     /etc/nginx/certs/modern.crt;
    ssl_certificate_key /etc/nginx/certs/modern.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    location / {
      return 200 "OK - modern TLS\n";
    }
  }
}

