zone "weak.chaos.local" {
    type master;
    file "/etc/bind/zones/weak.chaos.local.zone";
};

zone "safe.chaos.local" {
    type master;
    file "/etc/bind/zones/safe.chaos.local.zone";
};

zone "broken.chaos.local" {
    type master;
    file "/etc/bind/zones/broken.chaos.local.zone";
};

zone "unsigned.chaos.local" {
    type master;
    file "/etc/bind/zones/unsigned.chaos.local.zone";
};
