#!/usr/bin/env python3
"""COV-01 generator: derives docs/uat-coverage-gaps.md from docs/UAT-SERIES.md at run time.

Why this exists (204-CONTEXT.md D-07/D-08): the file this replaces hard-coded its own totals and a
frozen series bound in its header, sourced from a bucket-scoped historical ledger that structurally
cannot cover every series in the corpus. This generator reads the live document, computes every
number it prints, and covers all series present in the corpus -- not a bound baked in at authoring
time. The historical disposition evidence file this project also keeps is deliberately never opened
here (204-CONTEXT.md D-02): it is retained as evidence for how past conflicts were resolved, not as
a live input to this generator.

Parser reuse discipline: this module imports scripts/uat_corpus.py's grammar and reconciliation
directly -- it does not re-derive a second, divergent case-ID or Result-line pattern. The only
pattern defined locally is a title-capture regex built on top of the imported case-ID pattern, so a
heading's free-text title can be shown in the worklist table.

Determinism requirements (what makes the byte-reproducibility gate in
tests/test_uat_coverage_gaps_freshness.py meaningful): no wall-clock timestamp, no absolute path in
the output, a stable sort (series numerically, then case id), a single trailing newline, and LF line
endings throughout.

Regenerate with: `python -m scripts.generate_uat_coverage_gaps > docs/uat-coverage-gaps.md`
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Optional

from scripts import uat_corpus as corpus

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "uat-coverage-gaps.md"
REGEN_COMMAND = "python -m scripts.generate_uat_coverage_gaps > docs/uat-coverage-gaps.md"

# Built on top of the imported case-ID grammar -- not a second, divergent case-ID pattern. Captures
# only the free-text title trailing the heading's case id, for display purposes.
TITLE_RE = re.compile(r"^### *" + corpus.CASE_ID_PATTERN + r":?\s*(.*)$")

_GAP_PREFIX_RE = re.compile(r"^GAP\s*[—-]\s*", re.IGNORECASE)
_OBSOLETE_PREFIX_RE = re.compile(r"^OBSOLETE\s*[—-]\s*", re.IGNORECASE)


def _extract_titles(lines: list) -> dict:
    """Map heading line number -> free-text case title, read from the same lines the parser scans."""
    titles = {}
    for lineno, raw in enumerate(lines, start=1):
        line = raw.rstrip("\n").rstrip("\r")
        m = TITLE_RE.match(line)
        if m:
            titles[lineno] = m.group(1).strip()
    return titles


def _escape_cell(text: str) -> str:
    return (text or "").replace("|", "\\|").strip()


def _gap_needed_text(case) -> str:
    """The coverage-that-would-be-needed clause, taken from the case's own annotation (Result-line
    GAP) or its own Notes-line GAP string (Notes-only GAP) -- never a second, guessed source."""
    raw = case.annotation if case.disposition == "GAP" else (case.notes_text or "")
    raw = (raw or "").strip()
    return _GAP_PREFIX_RE.sub("", raw).strip()


def _obsolete_reason_text(case) -> str:
    raw = (case.annotation or "").strip()
    return _OBSOLETE_PREFIX_RE.sub("", raw).strip()


def _series_range(cases: list) -> str:
    numeric_values = []
    for c in cases:
        key = corpus._series_sort_key(c.series)
        if key[0] == 0:
            numeric_values.append(key[1])
    if not numeric_values:
        return "n/a"
    numeric_values.sort()

    def _fmt(v: float) -> str:
        return str(int(v)) if float(v).is_integer() else str(v)

    return f"{_fmt(numeric_values[0])}-{_fmt(numeric_values[-1])}"


def build_worklist(lines: list) -> str:
    """Pure function: corpus lines in, complete worklist text out. No file I/O, no wall-clock
    reads -- this is what tests/test_uat_coverage_gaps_freshness.py drives its fixtures through."""
    cases = list(corpus.iter_cases(lines))
    titles = _extract_titles(lines)
    by_id = {c.case_id: c for c in cases}

    # The historical evidence file is never read here (204-CONTEXT.md D-02) -- an empty ledger-rows
    # list still gives correct total_headings / disposition_counts / doc_gap_ids / retired_obsolete_ids,
    # since only the cause-2..5 ledger-comparison fields (unused below) depend on ledger_rows.
    r = corpus.reconcile(cases, [])

    gap_cases = [by_id[cid] for cid in r.doc_gap_ids]
    gap_cases.sort(key=lambda c: (corpus._series_sort_key(c.series), c.case_id))

    obsolete_cases = [by_id[cid] for cid in r.retired_obsolete_ids]
    obsolete_cases.sort(key=lambda c: (corpus._series_sort_key(c.series), c.case_id))

    disposition_line = ", ".join(f"{k} {v}" for k, v in sorted(r.disposition_counts.items()))

    out = []
    out.append("# UAT Coverage Gaps Worklist")
    out.append("")
    out.append(f"**Generated by:** `scripts/generate_uat_coverage_gaps.py` -- do not hand-edit.")
    out.append("**Generated from:** `docs/UAT-SERIES.md`, parsed at run time via `scripts/uat_corpus.py`.")
    out.append(f"**Regenerate with:** `{REGEN_COMMAND}`")
    out.append("")
    out.append(
        "Every total below is computed by the generator at generation time from the live corpus. "
        "None is a frozen count carried forward from a prior run -- if you are about to cite a "
        "number from this file, prefer re-running the regeneration command above and citing that "
        "output instead. The historical per-case disposition evidence this project also keeps is "
        "retained as evidence only and is never read by this generator."
    )
    out.append("")
    out.append("## Totals")
    out.append("")
    out.append(f"- Total case headings: {r.total_headings}")
    out.append(f"- Disposition counts: {disposition_line}")
    out.append(f"- Open GAP (drainable) cases: {len(gap_cases)}")
    out.append(f"- Retired OBSOLETE cases (excluded from the open-GAP total below): {len(obsolete_cases)}")
    out.append(f"- Series range observed: {_series_range(cases)}")
    out.append("")
    out.append(f"## Open GAP Worklist ({len(gap_cases)} cases, all series)")
    out.append("")
    out.append("| Case ID | Series | Case Title | Coverage That Would Be Needed |")
    out.append("|---|---|---|---|")
    for c in gap_cases:
        title = _escape_cell(titles.get(c.heading_lineno, ""))
        needed = _escape_cell(_gap_needed_text(c))
        out.append(f"| {c.case_id} | {c.series} | {title} | {needed} |")
    out.append("")
    out.append(f"## Retired (OBSOLETE) -- {len(obsolete_cases)} cases, excluded from the open-GAP total")
    out.append("")
    out.append(
        "Cases below were dispositioned `OBSOLETE` (COV-09) and are explicitly excluded from the "
        "open-GAP total above -- a retirement never reappears as drainable work on any regeneration."
    )
    out.append("")
    out.append("| Case ID | Series | Case Title | Retirement Reason |")
    out.append("|---|---|---|---|")
    for c in obsolete_cases:
        title = _escape_cell(titles.get(c.heading_lineno, ""))
        reason = _escape_cell(_obsolete_reason_text(c))
        out.append(f"| {c.case_id} | {c.series} | {title} | {reason} |")
    out.append("")
    return "\n".join(out) + "\n"


def generate(series_path: Optional[Path] = None) -> str:
    path = series_path if series_path is not None else corpus.UAT_SERIES_PATH
    lines = corpus._read_lines(path)
    return build_worklist(lines)


def main(argv=None) -> int:
    sys.stdout.write(generate())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
