ssl = yes
ssl_cert = </etc/dovecot/private/dovecot.crt
ssl_key  = </etc/dovecot/private/dovecot.key

# Force RSA non-PFS at TLS 1.2
ssl_min_protocol = TLSv1.2
ssl_cipher_list = AES128-SHA:AES256-SHA:!ECDHE:!DHE:!EDH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5
ssl_prefer_server_ciphers = yes
