protocols = imap pop3
listen = *
disable_plaintext_auth = no
auth_mechanisms = plain login
mail_location = maildir:/var/mail/%u
log_path = /dev/stderr
info_log_path = /dev/stdout

service imap-login {
  inet_listener imap {
    port = 143
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service pop3-login {
  inet_listener pop3 {
    port = 110
  }
  inet_listener pop3s {
    port = 995
    ssl = yes
  }
}

passdb {
  driver = static
  args = password=quirk allow_all_users=yes
}

userdb {
  driver = static
  args = uid=1000 gid=1000 home=/var/mail/%u
}

!include conf.d/10-ssl.conf
